project_name: Plywood Gallery - 3DArray
repository_url: https://github.com/kolibril13/plywood-gallery-3D-array
user_content_version: 1.22.3 (Numpy)
description: |
  Cheat sheet gallery for 3D array
favicon: icon.png
preview_image: https://kolibril13.github.io/plywood-gallery-3D-array/preview_image.png
gallery_parameters_path: gallery_assets/gallery_parameters.json




